package com.example.generadorcurp.form.domain

val estadosMexicanos = listOf(
    "AS" to "Aguascalientes",
    "BC" to "Baja California",
    "BS" to "Baja California Sur",
    "CC" to "Campeche",
    "CL" to "Coahuila",
    "CM" to "Colima",
    "CS" to "Chiapas",
    "CH" to "Chihuahua",
    "DF" to "Ciudad de México",
    "DG" to "Durango",
    "GT" to "Guanajuato",
    "GR" to "Guerrero",
    "HG" to "Hidalgo",
    "JC" to "Jalisco",
    "MC" to "Estado de México",
    "MN" to "Michoacán",
    "MS" to "Morelos",
    "NT" to "Nayarit",
    "NL" to "Nuevo León",
    "OC" to "Oaxaca",
    "PL" to "Puebla",
    "QT" to "Querétaro",
    "QR" to "Quintana Roo",
    "SP" to "San Luis Potosí",
    "SL" to "Sinaloa",
    "SR" to "Sonora",
    "TC" to "Tabasco",
    "TS" to "Tamaulipas",
    "TL" to "Tlaxcala",
    "VZ" to "Veracruz",
    "YN" to "Yucatán",
    "ZS" to "Zacatecas",
    "NE" to "Nacido en el extranjero"
)