package com.lanazirot.curpavanzado.domain.enums
enum class State (val stateName: String, val abbreviation: String) {
    AGUASCALIENTES("Aguascalientes", "AS"),
    BAJA_CALIFORNIA("Baja California", "BC"),
    BAJA_CALIFORNIA_SUR("Baja California Sur", "BS"),
    CAMPECHE("Campeche", "CM"),
    COAHUILA("Coahuila", "CO"),
    COLIMA("Colima", "CL"),
    CHIAPAS("Chiapas", "CS"),
    CHIHUAHUA("Chihuahua", "CH"),
    CIUDAD_DE_MEXICO("Ciudad de México", "DF"),
    DISTRICTO_FEDERAL("Distrito Federal", "DF"),
    DURANGO("Durango", "DG"),
    GUANAJUATO("Guanajuato", "GT"),
    GUERRERO("Guerrero", "GR"),
    HIDALGO("Hidalgo", "HG"),
    JALISCO("Jalisco", "JC"),
    MEXICO("México", "EM"),
    MICHOACAN("Michoacán", "MI"),
    MORELOS("Morelos", "MO"),
    NAYARIT("Nayarit", "NA"),
    NUEVO_LEON("Nuevo León", "NL"),
    OAXACA("Oaxaca", "OA"),
    PUEBLA("Puebla", "PU"),
    QUERETARO("Querétaro", "QT"),
    QUINTANA_ROO("Quintana Roo", "QR"),
    SAN_LUIS_POTOSI("San Luis Potosí", "SL"),
    SINALOA("Sinaloa", "SI"),
    SONORA("Sonora", "SO"),
    TABASCO("Tabasco", "TB"),
    TAMAULIPAS("Tamaulipas", "TS"),
    TLAXCALA("Tlaxcala", "TL"),
    VERACRUZ("Veracruz", "VE"),
    YUCATAN("Yucatán", "YU"),
    ZACATECAS("Zacatecas", "ZA")
}